/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.nikolay_martynov.java_coding_problems;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
